[package]
name = "wormtongue"
version = "0.1.0"
authors = ["Stephen Halwes <shalwes@pretalen.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
